project:
  type: website
  output-dir: docs

website:
  title: "LS 빅데이터쿨 4기 Qmd 블로그"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/soohyhy/soo-blog
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
